/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goldminer.gui;

import goldminer.game.enums.GameObjectType;
import static goldminer.game.enums.GameObjectType.GOLDMAN;
import goldminer.game.enums.MovingDirection;
import static goldminer.game.enums.MovingDirection.DOWN;
import static goldminer.game.enums.MovingDirection.LEFT;
import static goldminer.game.enums.MovingDirection.RIGHT;
import static goldminer.game.enums.MovingDirection.UP;
import goldminer.objects.common.AbstractGameObject;
import goldminer.objects.common.AbstractMovingObject;
import goldminer.objects.interfaces.gameMap.DrawableMap;
import goldminer.objects.interfaces.gameObject.MovingObject;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author lakobib
 */
public class Game extends ShablonFrame  implements ActionListener{

    private DrawableMap gameMap;
    private ActionListener listener;
    
    public Game() {
        initComponents();
    }

    void setMap(DrawableMap gameMap) {
       this.gameMap = gameMap;
       gameMap.drawMap();
       
       panelGameField.removeAll();
       panelGameField.add(gameMap.getMapComponent()); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        panelGameField = new javax.swing.JPanel();
        panelCommandField = new javax.swing.JPanel();
        buttonUp = new javax.swing.JButton();
        butLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        lblTurn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPoint = new javax.swing.JLabel();
        lblPoints = new javax.swing.JLabel();
        lblbTurns = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        meItSave = new javax.swing.JMenuItem();
        meItExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        meItStatistic = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        panelGameField.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout panelGameFieldLayout = new javax.swing.GroupLayout(panelGameField);
        panelGameField.setLayout(panelGameFieldLayout);
        panelGameFieldLayout.setHorizontalGroup(
            panelGameFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        panelGameFieldLayout.setVerticalGroup(
            panelGameFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelCommandField.setBorder(new javax.swing.border.MatteBorder(null));

        buttonUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldminer/images/up.png"))); // NOI18N
        buttonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpActionPerformed(evt);
            }
        });

        butLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldminer/images/left.png"))); // NOI18N
        butLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLeftActionPerformed(evt);
            }
        });

        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldminer/images/right.png"))); // NOI18N
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        btnDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldminer/images/down.png"))); // NOI18N
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });

        lblTurn.setText("Number of Turns");

        lblPoint.setText("Number of points");

        lblPoints.setText("0");

        lblbTurns.setText("0");

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldminer/images/save.png"))); // NOI18N
        btnSave.setText("Save");

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldminer/images/exit.png"))); // NOI18N
        btnExit.setText("Exit");

        javax.swing.GroupLayout panelCommandFieldLayout = new javax.swing.GroupLayout(panelCommandField);
        panelCommandField.setLayout(panelCommandFieldLayout);
        panelCommandFieldLayout.setHorizontalGroup(
            panelCommandFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCommandFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCommandFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCommandFieldLayout.createSequentialGroup()
                        .addGroup(panelCommandFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelCommandFieldLayout.createSequentialGroup()
                                .addComponent(butLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))
                    .addGroup(panelCommandFieldLayout.createSequentialGroup()
                        .addGroup(panelCommandFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCommandFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelCommandFieldLayout.createSequentialGroup()
                                    .addComponent(lblTurn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblbTurns)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2))
                                .addGroup(panelCommandFieldLayout.createSequentialGroup()
                                    .addComponent(lblPoint)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblPoints))))
                        .addContainerGap(49, Short.MAX_VALUE))))
            .addGroup(panelCommandFieldLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelCommandFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonUp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCommandFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        panelCommandFieldLayout.setVerticalGroup(
            panelCommandFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCommandFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonUp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCommandFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCommandFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTurn)
                    .addComponent(jLabel2)
                    .addComponent(lblbTurns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCommandFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPoint)
                    .addComponent(lblPoints))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu2.setText("Game");

        meItSave.setText("Save game");
        meItSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItSaveActionPerformed(evt);
            }
        });
        jMenu2.add(meItSave);

        meItExit.setText("Exit");
        jMenu2.add(meItExit);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");

        meItStatistic.setText("Statistic");
        jMenu3.add(meItStatistic);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCommandField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelGameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCommandField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meItSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meItSaveActionPerformed

    private void buttonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpActionPerformed
        moveOject(UP,GOLDMAN);
    }//GEN-LAST:event_buttonUpActionPerformed

    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownActionPerformed
        moveOject(DOWN,GOLDMAN);
    }//GEN-LAST:event_btnDownActionPerformed

    private void butLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLeftActionPerformed
        moveOject(LEFT,GOLDMAN);
    }//GEN-LAST:event_butLeftActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        moveOject(RIGHT,GOLDMAN);
    }//GEN-LAST:event_btnRightActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton butLeft;
    private javax.swing.JButton buttonUp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblPoint;
    private javax.swing.JLabel lblPoints;
    private javax.swing.JLabel lblTurn;
    private javax.swing.JLabel lblbTurns;
    private javax.swing.JMenuItem meItExit;
    private javax.swing.JMenuItem meItSave;
    private javax.swing.JMenuItem meItStatistic;
    private javax.swing.JPanel panelCommandField;
    private javax.swing.JPanel panelGameField;
    // End of variables declaration//GEN-END:variables



    private void moveOject (MovingDirection movingDirection, GameObjectType gameObjectType){
/*        AbstractGameObject gameObject = gameMap.getMap().getObjectsByType(gameObjectType).get(0);
        
        gameMap.getMap().move();
       
        if (gameObject instanceof MovingObject) {
            ((AbstractMovingObject)gameObject).Move(movingDirection);
            gameMap.drawMap();
        }
*/
        gameMap.getMap().move(movingDirection, gameObjectType);
        gameMap.drawMap();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    


}
